---
title: "Merging Blocks and TAZs"
author: "Author Goes Here"
date: "`r Sys.Date()`"
format: 
  html: 
    self-contained: true
editor: visual
---

## Goal

We want a way to allocate census information into TAZs. TAZs are made up of census blocks, but sometimes split the blocks. We want to create a table that gives us a way to allocate census factors into TAZs.

### Set up Packages

```{r}
library(tidyverse)
library(tidycensus)
library(tigris)
library(mapview)
library(sf)
```

## Load shapes

```{r}
#| results: hide
 
#Load TAZ shapes
TAZ <- sf::read_sf("J:/Shared drives/Data_Requests/TAZ_Shapefiles/R_Script/out/geopackage/TAZ19.gpkg") %>% 
  st_transform(26986)
# Load census block groups (other geography) tigris::block_groups()
# intersect them
# bring in building footprints
# find number of structures in each intersection
# also want to do share of land area--remove water?
# summarize
# output

cbtrue <- tigris::tracts(state = "MA", cb = TRUE, year = 2020)%>% 
  st_transform(26986)
cbfalse <- tigris::tracts(state = "MA", cb = FALSE, year = 2020) %>% 
  st_transform(26986)

mapview(cbfalse) + mapview(TAZ, col.regions = "red") + mapview(cbtrue, col.regions = "yellow")


# massgis census: https://www.mass.gov/info-details/massgis-data-2020-us-census

#massgis rooftops: https://www.mass.gov/info-details/massgis-data-building-structures-2-d
# rooftops <- st_read("data/base/STRUCTURES_POLY.shp")
 
# subset <- head(rooftops, 10)
# mapview(cbfalse) + mapview(subset)
# 
# saveRDS(rooftops, "data/processed/rooftops.rds")

rooftops <- read_rds("data/processed/rooftops.rds")




# problems that might come up. TAZ to census boundaries might be different (like microscopically different).

# find out which "block" shapes are used to create TAZs
# tiger/cartographic/state via massGIS.

# SPA give the TAZ geometry.
```

## Perform Intersections

### Intersections

```{r}
intersections <- st_intersection(TAZ, cbfalse)
mapview(head(intersections,100))
```

### Look at Rooftop Share

```{r}

```

### Look at Area Share

```{r}

```

## Testing

### Test minority share

```{r}

```
