---
title: "block_to_TAZ_vehicles"
author: "Joe Delorto"
format: html
editor: visual
---

The purpose of this notebook is to confirm whether we can multiply the factors developed in the existing TAZ-blk spreadsheets to get the same TAZ populations that appear in source data.

```{r setup}
library(tidycensus)
library(tidyverse)
```

```{r variables}
vars <- load_variables(2010,"sf1")
```

```{r read_population}
# taz_2010block_allocation <- read.csv("data/base/taz_2010block_allocation.csv")
# 
# taz_2010block_assignment <- read.csv("data/base/taz_2010block_assignment.csv")

# J:\Shared drives\TMD_TSA\Data\GIS Data\correspondence_tables\archive\
taz_2010block_correspondence <- read.csv("data/base/sw_taz_ma_block2010_taz_correspondence.csv")

# Do this once then store as an RDS for quick loading.
# population_block <- get_decennial(geography = "block",
#                                   variables = "P001001",
#                                   year = 2010,
#                                   state = "MA")
#
# saveRDS(population_block, file = "./data/processed/pop10_blk.rds")

population_block <- readRDS("./data/processed/pop10_blk.rds")
```

This block is the first checkpoint just to make sure that my allocations are correct at the most basic level: total population.

```{r process_population}
taz_2010block_correspondence <- taz_2010block_correspondence |> 
  # Make chrs.
  mutate(
    STATE10 = as.character(STATE10),
    COUNTY10 = as.character(COUNTY10),
    TRACT10 = as.character(TRACT10),
    BLOCK10 = as.character(BLOCK10)
  ) |> 
  # add padding and paste together
  mutate(
    GEOID = paste0(
      str_pad(STATE10,  width = 2, side = "left", pad = 0),
      str_pad(COUNTY10, width = 3, side = "left", pad = 0),
      str_pad(TRACT10,  width = 6, side = "left", pad = 0),
      str_pad(BLOCK10,  width = 4, side = "left", pad = 0)
    )
  )

# join the datasets together to see where things agree
pop_TAZ_by_block <- inner_join(taz_2010block_correspondence, 
                               population_block,
                               by = "GEOID") |> 
  select(GEOID, TOWN10, TAZ:AREA_FCT, cen10_pop = value)

write_csv(pop_TAZ_by_block, "data/processed/pop_TAZ_by_block.csv")

rnd <- function(x) {trunc(x+sign(x)*0.5)}     ## rounding function

population_TAZ <- pop_TAZ_by_block %>%
  group_by(TAZ) %>%
  summarize(population = round(sum(POP_FCT * cen10_pop)),
            population_altrnd = rnd(sum(POP_FCT * cen10_pop)))

write_csv(population_TAZ, "output/data/population_TAZ.csv")
```

Let's read in what we think our "answer" should be: 
```{r}
# This is does not contain a population. 
# tdm19_taz_file <- read_csv("J:/Shared drives/TMD_TSA/Data/GIS Data/correspondence_tables/tdm19_taz_file.csv", show_col_types = FALSE)

# This is ostensibly the target spreadsheet?
target <- read_csv("./data/processed/pop_TAZ_by_block_assigned.csv", show_col_types = FALSE) |> 
  group_by(taz_id) |> 
  summarize(sum(value))
```

